# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:

  app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
        arguments:
            doctrine: "@doctrine"

  app.form.type.collaborator:
        class: AppBundle\Form\Type\CollaboratorType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type }

  form.flow.createForm:
    class: AppBundle\Form\CreateFormFlow
    parent: craue.form.flow
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
